# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is NOT reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# ============================================================
# SITE INFORMATION
# ============================================================

title: "Md Eyasin Ul Islam Pavel"

email: "mxp220120@utdallas.edu"

description: >-
  PhD Candidate in Public Affairs at the University of Texas at Dallas.
  Research interests include human resource management, organizational
  management, organizational theory, organizational capacity, innovation,
  performance, employee engagement, public management, quantitative methods,
  and emotional labor.

url: "https://eyasinpavel.github.io"

baseurl: "/pavel-website.github.io"

github_username: eyasinpavel


# ============================================================
# SITE FOOTER
# ============================================================

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github fa-3x"
      url: "https://github.com/eyasinpavel"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin fa-3x"
      url: ""


# ============================================================
# AUTHOR INFORMATION
# ============================================================

author:
  name: "Md Eyasin Ul Islam Pavel"

  bio: >-
    PhD Candidate in Public Affairs at the University of Texas at Dallas.

  location: "Dallas, TX, USA"

  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eyasinpavel"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: ""

    - label: "Google Scholar"
      icon: "ai ai-google-scholar-square"
      url: "https://scholar.google.com/citations?user=ayYdZcsAAAAJ&hl=en&authuser=2"


# ============================================================
# ATOM FEED
# ============================================================

atom_feed:
  hide: true


# ============================================================
# BUILD SETTINGS
# ============================================================

# theme: "minima"

remote_theme: "mmistakes/minimal-mistakes@4.23.0"

minimal_mistakes_skin: "dark"
# Available skins:
# "air"
# "aqua"
# "contrast"
# "dark"
# "dirt"
# "neon"
# "mint"
# "plum"
# "sunrise"


# ============================================================
# PLUGINS
# ============================================================

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji


# ============================================================
# DEFAULTS
# ============================================================

defaults:

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


# ============================================================
# INCLUDE
# ============================================================

include:
  - _pages


# ============================================================
# EXCLUDE FROM PROCESSING
# ============================================================

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - path/ruby/3.0.0/gems/
  - path/ruby/3.0.0/
